services:
  - type: web
    name: jawraa-website
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: CONTACT_FROM_EMAIL
        sync: false
